services:
  app:
    build: .
    container_name: yellow-luke-2
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./servers.json:/app/servers.json
      - ./textChannelPlayers.json:/app/textChannelPlayers.json
      - ./mapUrl.json:/app/mapUrl.json:ro
