version: '3.9'

services:
  mongodb:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword123xD
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb_data:/data/db
    logging:
      options:
        max-size: 100m
    restart: always
  yellowluke:
    depends_on:
      - mongodb
    restart: on-failure
    build: .
